excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing                         
  - conditional_returns_on_newline          
  - empty_count                             
  - explicit_init                           
  - fatal_error_message                     
  - file_header                             
  - first_where                             
  - force_unwrapping                        
  - implicitly_unwrapped_optional           
  - multiline_parameters                    
  - nimble_operator                         
  - number_separator                        
  #- object_literal                          
  - operator_usage_whitespace               
  - overridden_super_call                   
  - private_outlet                          
  - prohibited_super_call                   
  - redundant_nil_coalescing                
  - sorted_imports                          
  - switch_case_on_newline                  
  - trailing_closure
  - vertical_parameter_alignment_on_call    


reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
